/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_cognito_identity_pool_id:
    "ap-south-1:4f8660b6-d960-4023-89db-84eba43f9a59",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_uRO6eZxzg",
  aws_user_pools_web_client_id: "3545ehvcp40bcdoti9p2hfgl36",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL", "NAME"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS",
      "REQUIRES_UPPERCASE",
    ],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint:
    "https://mkvkex6eojanpfhep2rr2unriu.appsync-api.ap-south-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-south-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-5qfqyynkurabfivjqn5ipdm5vi",
  aws_user_files_s3_bucket: "resumer-storage165434-staging",
  aws_user_files_s3_bucket_region: "ap-south-1",
};

export default awsmobile;
